Almanac/Website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func
class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class file(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(1500))
    first_name =  db.Column(db.String(150))
    notes = db.relationship('Note')
    files = db.relationship('file')
    assigns = db.relationship('assigns')

class assigns(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    description = db.Column(db.String(2000))  
    subject = db.Column(db.String(30))
    deadline = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


Almanac/Website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path 
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'abcdef'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database(app):
    if not path.exists('Website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created database!')

Almanac/Website/auth.py
from flask import Blueprint, render_template, request, flash, redirect , url_for
from flask_login import login_user, login_required, logout_user, current_user
from Website import views
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password, Try again.', category='error')

        else:
            flash('Email Does not Exist',category='error')

            

    return render_template("login.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method=="POST":
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        if(len(email))<4:
            flash('Email Must be greater than 4 characters', category="error")
        elif len(first_name) < 2:
            flash('First Name Must be greater than 3 characters', category="error")
        elif password1 != password2:
            flash('Passwords dont match', category="error")
        elif( len(password1))<7:
            flash('Password Must be greater than 7 characters', category="error")
        else:
            new_user = User(email=email, first_name = first_name, password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)

            flash("Account Created", category="success")
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

Almanac/Website/views.py
import os, sqlite3
from datetime import datetime
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, send_file
from werkzeug.utils import secure_filename
from flask_login import login_required, current_user
from .models import Note, file, User, assigns

from . import db 
import json
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')
        if(len(note) < 1):
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note Added!', category='success')
    return render_template("home.html", user=current_user)

@views.route('/delete-note',methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
    
    return jsonify({})


@views.route('/delete-file/<int:file_id>', methods=['DELETE'])
def delete_file(file_id):
        file_data = json.loads(request.data)
        f = file.query.get(file_id)
        if f and f.user_id == current_user.id:
            db.session.delete(f)
            file_path = os.path.join('uploads/', f.author)
            os.remove(file_path)
            db.session.commit()
            
            flash("Deleted Successfully", category="success")
        else:
            flash("Error", category="failure")


@views.route('/upload-pdf-note', methods=['POST'])
def upload_note():
    
    if 'file' in request.files:
        f = request.files['file']
        filename = secure_filename(f.filename)
        f.save(os.path.join('uploads', filename))

        new_file = file(author=filename, user_id=current_user.id)
        db.session.add(new_file)
        db.session.commit()
        flash('Note Uploaded!', category='success')
        
    else:
        flash("No File Selected", category='failure')
   
    return redirect(url_for('views.home'))


@views.route('/library')
@login_required
def library():
    pdf_files = file.query.all()
    return render_template('library.html',user=current_user, pdf_files=pdf_files, User=User)

@views.route('/download-pdf/<filename>')
def download_pdf(filename):
    path = 'D:/Arshnoor/Almanac/uploads/' + filename
    return send_file(path, as_attachment=True)


@views.route('/assignments')
def assignments():
    return render_template('assignments.html', user=current_user, all_users = User, assigns = assigns.query.all())

@views.route('/publish-assign', methods=['POST'])
def new_assignemnt():
    title = request.form.get('title')
    date = datetime.strptime(request.form.get('deadline'), '%Y-%m-%d') 
    subject = request.form.get('subject')
    description = request.form.get('description')

    new = assigns(title=title, deadline=date, description=description, subject=subject, user_id=current_user.id)
    db.session.add(new)
    db.session.commit()
    flash('Assignment Published!', category='success')

    return redirect(url_for('views.assignments'))

Almanac/Website/templates/assignments.html
{% extends "base.html"  %} {% block title  %}Assignments{% endblock %}

{% block content %}
    <h1>Assignments</h1>
    
        {% for a in assigns %}
        <div class="alert alert-dark" role="alert">
            
            {{ a.title }}
            {{ a.subject }}
            {{ a.deadline }}
            {{ a.description }}
            ~ POSTED BY {{ all_users.query.get(a.id).first_name }}
            
            
        </div>
        {% endfor %}


    
        {% block posting %}
        <div class=" fixed-bottom" >
            <form method="POST" action="/publish-assign">
                <span class="d-block p-2 bg-dark text-white">
                <h5>Post New Assignment</h5>
                <input name='title' placeholder="Title">
                <input name='subject' placeholder="Subject">
                <input name='deadline'  type="date" placeholder="Due Date">
                <br />
                <br />
                <textarea name="description" class="form-control" placeholder="Enter Assignment Description..."></textarea> 
                <br />
                <button type="submit" class="btn btn-light">Publish</button>
                </span>
            </form>

        </div>
        {% endblock %}
{% endblock %}

Almanac/Website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
        />
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
        />

        <title>{% block title  %}HOME{% endblock %}</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                    <div class="navbar-nav">
                        {% if user.is_authenticated  %}
                        <a class="nav-item nav-link" id="home" href="/">Home</a>
                        <a class="nav-item nav-link" id="library" href="/library">Library</a>
                        <a class="nav-item nav-link" id="assignments" href="/assignments">Assignments</a>
                        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" id="login" href="/login">Login</a>
                        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                        {% endif %}
                        
                    </div>
                    
            </div>
            
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>

      <script 
        type="text/javascript"
        src="{{ url_for('static', filename='index.js')}}"
      ></script>  
    </body>
</html>

Almanac/Website/templates/home.html
{% extends "base.html"  %} {% block title  %}Home{% endblock %}

{% block content %}
<h1 style="font-family: 'Times New Roman', serif;" align="center">Almanac</h1>
<h2 style="font-family: 'Times New Roman', serif;" align="left">Notes</h2>
<ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">
        {{ note.data }}
        <button type="button" class="close" onClick="deleteNote({{ note.id}})">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>
<br />
<h2 style="font-family: 'Times New Roman', serif;" align="left">Files</h2>
<ul class="list-group list-group-flush" id="files">
    {% for f in user.files %}
    <li class="list-group-item">
        {{ f.author }} - <button class="btn btn-danger" onclick="deleteFile({{ f.id }})">Delete</button>
    </li>
    {% endfor %}
</ul>

<br />

<form method='POST'>
    <textarea name="note" id="note" class="form-control"></textarea>
    <br />
    <div align="right">
        <button type="submit" class="btn btn-primary">Add Note</button>
        
    </div>
</form>
<br />

<form action="/upload-pdf-note" method="POST" enctype="multipart/form-data">
    <div align="right">
    <input type="file" name="file" class="form-control" accept=".pdf" required>
    <button type="submit" class="btn btn-primary">Upload</button>
    </div>

</form>
{% endblock %}

Almanac/Website/templates/library.html
{% extends "base.html"  %} {% block title  %}Library{% endblock %}

{% block content %}

    <h2>Library</h2>
    <ul>
        {% for file in pdf_files %}
        
            <li>
                <div class="files">
                {{ file.author }} - Owner: {{ User.query.get(file.user_id).first_name }}
                <a href="{{ url_for('views.download_pdf', filename=file.author) }}">
                    <img src="https://cdn3.iconfinder.com/data/icons/sympletts-part-3/128/cloud-download-512.png" alt="Download" height="32"  >
                </a>
                </div>
            </li>
        
        {% endfor %}
    </ul>

    
{% endblock %}

Almanac/Website/templates/login.html
{% extends "base.html"  %} {% block title  %}Login{% endblock %}

{% block content %}
<form method="POST">
    <br />
    <h3 align="center">Login</h3>
    <img src="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/user.png" alt="user" height="64" class="rounded mx-auto d-block">
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email"/>

    </div>
    
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password"/>
        
    </div>
    
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Almanac/Website/templates/sign_up.html
{% extends "base.html"  %} {% block title  %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email"/>

    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name"/>
        
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password"/>
        
    </div>
    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password"/>
        
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}